-- Esquema operativo de clinica-bd (auth + clínica).
-- Usuarios, roles, pacientes, diagnósticos, recetas, etc. viven acá,
-- junto con las tablas Dim/Hecho de reportes (create_reportes_tables.sql).
-- Idempotente: se puede ejecutar más de una vez.
--
-- Uso:
--   npm run migrate:reportes
--   npm run seed

BEGIN;

-- Auth

CREATE TABLE IF NOT EXISTS rol (
  "idRol" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL UNIQUE,
  descripcion VARCHAR(500),
  "isActive" BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS permisos (
  "idPermiso" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL UNIQUE,
  descripcion VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS permisos_rol (
  "idRol" INTEGER NOT NULL,
  "idPermiso" INTEGER NOT NULL,
  PRIMARY KEY ("idRol", "idPermiso"),
  CONSTRAINT "FK_permisos_rol_rol"
    FOREIGN KEY ("idRol") REFERENCES rol ("idRol"),
  CONSTRAINT "FK_permisos_rol_permiso"
    FOREIGN KEY ("idPermiso") REFERENCES permisos ("idPermiso")
);

CREATE TABLE IF NOT EXISTS usuario (
  "idUsuario" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  estado BOOLEAN NOT NULL DEFAULT true,
  "idRol" INTEGER,
  CONSTRAINT "FK_usuario_rol"
    FOREIGN KEY ("idRol") REFERENCES rol ("idRol")
);

-- Organización

CREATE TABLE IF NOT EXISTS area (
  "idArea" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descripcion VARCHAR(255) NOT NULL,
  "isActive" BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS sede (
  "idSede" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  direccion VARCHAR(500),
  "isActive" BOOLEAN NOT NULL DEFAULT true
);

-- Personas (PK = idUsuario)

CREATE TABLE IF NOT EXISTS paciente (
  "idPaciente" INTEGER PRIMARY KEY,
  "dniPaciente" VARCHAR(20) NOT NULL UNIQUE,
  "nombrePaciente" VARCHAR(255) NOT NULL,
  "edadPaciente" INTEGER NOT NULL,
  "generoPaciente" VARCHAR(20) NOT NULL,
  "direccionPaciente" VARCHAR(500),
  "telefonoPaciente" VARCHAR(20),
  "fechaNacimiento" DATE NOT NULL,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  CONSTRAINT "FK_paciente_usuario"
    FOREIGN KEY ("idPaciente") REFERENCES usuario ("idUsuario")
);

CREATE TABLE IF NOT EXISTS medico (
  "idMedico" INTEGER PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  genero VARCHAR(20) NOT NULL,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "idArea" INTEGER,
  "idSede" INTEGER,
  CONSTRAINT "FK_medico_usuario"
    FOREIGN KEY ("idMedico") REFERENCES usuario ("idUsuario"),
  CONSTRAINT "FK_medico_area"
    FOREIGN KEY ("idArea") REFERENCES area ("idArea"),
  CONSTRAINT "FK_medico_sede"
    FOREIGN KEY ("idSede") REFERENCES sede ("idSede")
);

-- Clínica

CREATE TABLE IF NOT EXISTS historia_clinica (
  "idHistoriaClinica" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idPaciente" INTEGER NOT NULL UNIQUE,
  estado VARCHAR(50) NOT NULL DEFAULT 'activa',
  "fechaIngreso" DATE NOT NULL DEFAULT CURRENT_DATE,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  CONSTRAINT "FK_historia_paciente"
    FOREIGN KEY ("idPaciente") REFERENCES paciente ("idPaciente")
);

CREATE TABLE IF NOT EXISTS tratamiento (
  "idTratamiento" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  descripcion VARCHAR(255) NOT NULL,
  bloqueado BOOLEAN NOT NULL DEFAULT false,
  "isActive" BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS diagnostico (
  "idDiagnostico" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idhistoriaClinica" INTEGER NOT NULL,
  "idMedico" INTEGER NOT NULL,
  "fechaDiagnostico" DATE NOT NULL,
  "estadoSalud" VARCHAR(100) NOT NULL,
  "gradoEnfermedad" VARCHAR(100) NOT NULL,
  observaciones TEXT,
  es_diagnostico_inicial BOOLEAN NOT NULL DEFAULT false,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT "FK_diagnostico_historia"
    FOREIGN KEY ("idhistoriaClinica") REFERENCES historia_clinica ("idHistoriaClinica"),
  CONSTRAINT "FK_diagnostico_medico"
    FOREIGN KEY ("idMedico") REFERENCES medico ("idMedico")
);

CREATE TABLE IF NOT EXISTS receta (
  "idReceta" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Modelo_IA" VARCHAR(255) NOT NULL,
  "fechaReceta" DATE NOT NULL,
  "idDiagnostico" INTEGER UNIQUE,
  "idTratamiento" INTEGER NOT NULL,
  contenido TEXT,
  sustentacion TEXT,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT "FK_receta_diagnostico"
    FOREIGN KEY ("idDiagnostico") REFERENCES diagnostico ("idDiagnostico"),
  CONSTRAINT "FK_receta_tratamiento"
    FOREIGN KEY ("idTratamiento") REFERENCES tratamiento ("idTratamiento")
);

-- Indicadores

CREATE TABLE IF NOT EXISTS categoria_indicadores (
  "idTipoIndicador" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descripcion VARCHAR(255) NOT NULL,
  bloqueado BOOLEAN NOT NULL DEFAULT false,
  "isActive" BOOLEAN NOT NULL DEFAULT true
);

DO $$ BEGIN
  CREATE TYPE "public"."indicadores_clinicos_unidad_enum" AS ENUM('numero', 'texto', 'booleano');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS indicadores_clinicos (
  "idIndicador" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  descripcion VARCHAR(255) NOT NULL,
  unidad indicadores_clinicos_unidad_enum NOT NULL,
  bloqueado BOOLEAN NOT NULL DEFAULT false,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "idCategoriaIndicador" INTEGER,
  "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT "FK_indicador_categoria"
    FOREIGN KEY ("idCategoriaIndicador") REFERENCES categoria_indicadores ("idTipoIndicador")
);

CREATE TABLE IF NOT EXISTS diagnostico_indicador_clinico (
  "idDiagnosticoIndicador" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  valor VARCHAR(255) NOT NULL,
  "fechaMedicion" DATE NOT NULL,
  "idDiagnostico" INTEGER,
  "idIndicador" INTEGER,
  CONSTRAINT "UQ_dic_diagnostico_indicador" UNIQUE ("idDiagnostico", "idIndicador"),
  CONSTRAINT "FK_dic_diagnostico"
    FOREIGN KEY ("idDiagnostico") REFERENCES diagnostico ("idDiagnostico"),
  CONSTRAINT "FK_dic_indicador"
    FOREIGN KEY ("idIndicador") REFERENCES indicadores_clinicos ("idIndicador")
);

COMMIT;
