-- Reportes en la base principal (clinica-bd)
-- Crea las tablas dimensionales y de hechos que antes vivían en esclerosisd.
-- Idempotente: se puede ejecutar más de una vez.
--
-- Uso (PowerShell, desde esclerosis-back):
--   npm run migrate:schema
--
-- O con psql:
--   psql -h localhost -p 5432 -U postgres -d "clinica-bd" -f src/database/migrations/create_reportes_tables.sql

BEGIN;

-- Dimensiones

CREATE TABLE IF NOT EXISTS "DimOrganizacion" (
  "Organizacion_Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "NombreSede" VARCHAR(255) NOT NULL,
  direccion VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS "DimTiempo" (
  "Fecha_Id" INTEGER PRIMARY KEY,
  anio INTEGER NOT NULL,
  trimestre INTEGER NOT NULL,
  mes INTEGER NOT NULL,
  dia INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "DimMedico" (
  "Medico_Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Nombre" VARCHAR(255) NOT NULL,
  area VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS "DimModeloIA" (
  "Modelo_Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "NombreModelo" VARCHAR(255) NOT NULL,
  CONSTRAINT "UQ_DimModeloIA_NombreModelo" UNIQUE ("NombreModelo")
);

CREATE TABLE IF NOT EXISTS "DimPaciente" (
  "Paciente_Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "NumDocumento" VARCHAR(50) NOT NULL,
  nombre VARCHAR(255) NOT NULL,
  genero VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS "DimIndicadoresClinicos" (
  "Indicador_Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "NombreIndicador" VARCHAR(255) NOT NULL,
  "CategoriaIndicador" VARCHAR(255),
  "ValorIndicador" DOUBLE PRECISION
);

-- Hechos

CREATE TABLE IF NOT EXISTS "HechoRecetas" (
  "HechoReceta_Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "modeloModeloId" INTEGER,
  "tiempoFechaId" INTEGER,
  "organizacionOrganizacionId" INTEGER,
  "medicoMedicoId" INTEGER,
  "CantidadRecetasGeneradasCopilot" INTEGER NOT NULL DEFAULT 0,
  "CantidadRecetasGeneradasDeepseek" INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT "FK_HechoRecetas_modelo"
    FOREIGN KEY ("modeloModeloId") REFERENCES "DimModeloIA" ("Modelo_Id"),
  CONSTRAINT "FK_HechoRecetas_tiempo"
    FOREIGN KEY ("tiempoFechaId") REFERENCES "DimTiempo" ("Fecha_Id"),
  CONSTRAINT "FK_HechoRecetas_organizacion"
    FOREIGN KEY ("organizacionOrganizacionId") REFERENCES "DimOrganizacion" ("Organizacion_Id"),
  CONSTRAINT "FK_HechoRecetas_medico"
    FOREIGN KEY ("medicoMedicoId") REFERENCES "DimMedico" ("Medico_Id")
);

CREATE TABLE IF NOT EXISTS "HechoIndicador" (
  "HechoIndicador_Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "indicadorIndicadorId" INTEGER,
  "pacientePacienteId" INTEGER,
  "tiempoFechaId" INTEGER,
  "medicoMedicoId" INTEGER,
  "organizacionOrganizacionId" INTEGER,
  "ValorPromedioIndicador" DOUBLE PRECISION,
  "ValorInicialIndicador" DOUBLE PRECISION,
  CONSTRAINT "FK_HechoIndicador_indicador"
    FOREIGN KEY ("indicadorIndicadorId") REFERENCES "DimIndicadoresClinicos" ("Indicador_Id"),
  CONSTRAINT "FK_HechoIndicador_paciente"
    FOREIGN KEY ("pacientePacienteId") REFERENCES "DimPaciente" ("Paciente_Id"),
  CONSTRAINT "FK_HechoIndicador_tiempo"
    FOREIGN KEY ("tiempoFechaId") REFERENCES "DimTiempo" ("Fecha_Id"),
  CONSTRAINT "FK_HechoIndicador_medico"
    FOREIGN KEY ("medicoMedicoId") REFERENCES "DimMedico" ("Medico_Id"),
  CONSTRAINT "FK_HechoIndicador_organizacion"
    FOREIGN KEY ("organizacionOrganizacionId") REFERENCES "DimOrganizacion" ("Organizacion_Id")
);

CREATE TABLE IF NOT EXISTS "HechoPacientesEM" (
  "HechoPacienteEM_Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "modeloModeloId" INTEGER,
  "pacientePacienteId" INTEGER,
  "tiempoFechaId" INTEGER,
  "medicoMedicoId" INTEGER,
  "organizacionOrganizacionId" INTEGER,
  "CantidadPacientesDiagnosticadosEM" INTEGER NOT NULL,
  CONSTRAINT "FK_HechoPacientesEM_modelo"
    FOREIGN KEY ("modeloModeloId") REFERENCES "DimModeloIA" ("Modelo_Id"),
  CONSTRAINT "FK_HechoPacientesEM_paciente"
    FOREIGN KEY ("pacientePacienteId") REFERENCES "DimPaciente" ("Paciente_Id"),
  CONSTRAINT "FK_HechoPacientesEM_tiempo"
    FOREIGN KEY ("tiempoFechaId") REFERENCES "DimTiempo" ("Fecha_Id"),
  CONSTRAINT "FK_HechoPacientesEM_medico"
    FOREIGN KEY ("medicoMedicoId") REFERENCES "DimMedico" ("Medico_Id"),
  CONSTRAINT "FK_HechoPacientesEM_organizacion"
    FOREIGN KEY ("organizacionOrganizacionId") REFERENCES "DimOrganizacion" ("Organizacion_Id")
);

CREATE TABLE IF NOT EXISTS "HechoPacientesAtendidos" (
  "HechoPacienteAtendido_Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "indicadorIndicadorId" INTEGER,
  "medicoMedicoId" INTEGER,
  "tiempoFechaId" INTEGER,
  "organizacionOrganizacionId" INTEGER,
  "CantidadPacientesAtendidos" INTEGER NOT NULL,
  CONSTRAINT "FK_HechoPacientesAtendidos_indicador"
    FOREIGN KEY ("indicadorIndicadorId") REFERENCES "DimIndicadoresClinicos" ("Indicador_Id"),
  CONSTRAINT "FK_HechoPacientesAtendidos_medico"
    FOREIGN KEY ("medicoMedicoId") REFERENCES "DimMedico" ("Medico_Id"),
  CONSTRAINT "FK_HechoPacientesAtendidos_tiempo"
    FOREIGN KEY ("tiempoFechaId") REFERENCES "DimTiempo" ("Fecha_Id"),
  CONSTRAINT "FK_HechoPacientesAtendidos_organizacion"
    FOREIGN KEY ("organizacionOrganizacionId") REFERENCES "DimOrganizacion" ("Organizacion_Id")
);

COMMIT;
